# Configuraci√≥n del Editor Panka

# Number of spaces for a tab.
tabSize = 4

# Whether to show line numbers on startup.
# Toggled in-app with Ctrl+L
showLineNumbers = true

# Whether to show non-printable characters like spaces, tabs, and newlines (toggled with Ctrl+O).
showNonPrintable = false

# Set to true to enable debug logging.
enableLogger = false